### ISSUE TITLE
Requirements.txt & documentation

### ISSUE THREAD

**Issue by sabueso** [ThePBone/GalaxyBuds-BatteryLevel#10]
Hi 

would be great to have a requirements.txt in the repo and some troubleshoot info: under a clean Ubuntu 20 instead "make pip install PyBluez" I've installed from the APT repo the packages "bluetooth python-bluez llibbluetooth-dev" (idk why, but only the pip package I've obtained an import bluetooth error )

Good work!
Cheers!

**Comment by timschneeb** [comment]
I've added a [requirements.txt](https://github.com/ThePBone/GalaxyBuds-BatteryLevel/blob/master/requirements.txt) file (although the only pip dependency is PyBluez anyway).

The packages are only necessary if your distro has no Bluetooth support preinstalled. I've added a note in the readme about this.
