### ISSUE TITLE
Error "ImportError: No module named bluetooth"

### ISSUE THREAD

**Issue by kred-jon** [ThePBone/GalaxyBuds-BatteryLevel#3]
Hello 
Great script to test run with "realme Buds Q"

Got an error when run the script;  python buds_battery.py [MACADDRESS] --monitor

Traceback (most recent call last):
  File "buds_battery.py", line 11, in <module>
    import bluetooth
ImportError: No module named bluetooth

Any ideas to help make it work?

Thanks.
Kred

**Comment by timschneeb** [comment]
Also, this script only works with the Samsung Galaxy Buds (Plus). **Realme Buds Q or other earbuds are not supported.**

Solution to your actual problem:

It looks like you are lacking the PyBluez python package.

If you're on Linux you can install it by executing a pip command in the terminal: 
`pip install PyBluez`

On Windows this is much harder, you may need to compile PyBluez from scratch. You can follow those instructions for example: <https://stackoverflow.com/questions/48821917/downloading-and-installing-pybluez-for-a-64-bit-windows-10-pc>
(Keep in mind that this script was designed to work on Linux; I don't know how well PyBluez works on Windows.)

**Comment by ThePBone** [comment]
Also, this script only works with the Samsung Galaxy Buds (Plus). **Realme Buds Q or other earbuds are not supported.**

**Comment by kred-jon** [comment]
running under Linux and the PyBluez installed.
![image](https://user-images.githubusercontent.com/38023611/89381418-b052bf80-d72b-11ea-9685-b5b611c924e8.png)

**Comment by kred-jon** [comment]
OK, running it after install "sudo apt-get install python-bluez"

However got error "Couldn't find the proprietary RFCOMM service" yes maybe need to find the RFCOMM for RealME

**Comment by timschneeb** [comment]
Again, this script only works with the Samsung Galaxy Buds and Buds Plus. It is not compatible with any other headset.  

You need to use to more general solution: <https://github.com/TheWeirdDev/Bluetooth_Headset_Battery_Level>
