### ISSUE TITLE
AUR package

### ISSUE THREAD

**Issue by AriaMoradi** [ThePBone/GalaxyBuds-BatteryLevel#5]
I made a AUR package for this repo: https://aur.archlinux.org/packages/galaxybuds-batterylevel-git/

I copy `buds_battery.py` to `/usr/bin` and rename it to `galaxybuds-batterylevel`.

Any opinions?

**Comment by timschneeb** [comment]
Thanks!
I've added your package and credits to the README.

**Comment by AriaMoradi** [comment]
@ThePBone just @ mention me if there is anything to do about it later.
