### ISSUE TITLE
Doesn't work on Galaxy buds+(SM-R175)

### ISSUE THREAD

**Issue by AriaMoradi** [ThePBone/GalaxyBuds-BatteryLevel#7]
Hey, I was using dfbb315 before, but the latest version fails to show load the data:

`Couldn't find the proprietary RFCOMM service`

**Comment by timschneeb** [comment]
The service lookup mechanism has been changed because some users with certain Bluetooth adapters had issues enumerating the Bluetooth services properly.
Also see #8
